[package]
name = "plivo-sdk-rust"
version = "0.1.0"
authors = ["hurnhu <hurnhu5622@gmail.com>"]

[dependencies]
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
reqwest = "0.9.20"
dotenv = "0.14.1"
url = "2.1.0"
