[package]
name = "plivo-sdk-rust"
version = "0.1.0"
authors = ["hurnhu <hurnhu5622@gmail.com>"]

[dependencies]
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
reqwest = "0.8.8"
dotenv = "0.13.0"
url = "1.7.1"
